on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        method: [global, corepack, prefix]
        check-latest: [true, false]
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [12, 20]
    runs-on: ${{ matrix.os }}

    name: method=${{ matrix.method }} check-latest=${{ matrix.check-latest }} os=${{ matrix.os }} node=${{ matrix.node-version }}

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - run: |
          set -x
          which npm
          npm --version
          which node
          node --version

      - run: corepack enable npm
        if: matrix.method == 'corepack'

      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: ${{ matrix.check-latest }}

      - run: |
          set -x
          which npm
          npm --version
          which node
          node --version

      - run: npm install -g $(jq -r '.packageManager' < package.json)
        if: matrix.method == 'global'

      - run: |
          export NPM_CONFIG_PREFIX=$HOME/.npm-global
          echo "NPM_CONFIG_PREFIX=$HOME/.npm-global" >> "$GITHUB_ENV"
          echo "$NPM_CONFIG_PREFIX/bin" >> $GITHUB_PATH
        if: matrix.method == 'prefix'

      - run: |
          set -x
          which npm
          npm --version
          which node
          node --version
